### ISSUE TITLE
parserOptions.project = true

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#1230]
> Perhaps `eslint-config-standard-with-typescript` could specify `parserOptions: { project: true }` so that the config can work without requiring an additional setup?

https://github.com/eslint/create-config/issues/71#issuecomment-1685273760

**Comment by meyfa** [comment]
This was a breaking change, unfortunately. Previously, the following worked:

```yaml
extends: standard
overrides:
  - files: ['*.ts', '*.tsx']
    extends: 'standard-with-typescript'
parserOptions:
  project: './tsconfig.lint.json'
```

but now we have to write:

```yaml
extends: standard
overrides:
  - files: ['*.ts', '*.tsx']
    extends: 'standard-with-typescript'
    parserOptions:
      project: './tsconfig.lint.json'
```

Additionally, it causes major effort for us. We're including eslint-config-standard-with-typescript in an org-wide custom config, which is then added to dozens of downstream projects. Now all of these downstream projects have to specify the `overrides` section as well, with the exact same files list as our custom config, for them to be able to set the project.

i.e. what worked before:

```yaml
extends: '@my-org/eslint-config'
parserOptions:
  project: './tsconfig.lint.json'
```

now has to be (in many repos):

```yaml
extends: '@my-org/eslint-config'
overrides:
  - files: ['*.ts', '*.tsx']
    parserOptions:
      project: './tsconfig.lint.json'
```

Otherwise, we get hit with the following error:

```
C:\Users\meyfa\project-name\test\index.test.ts
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/test\index.test.ts` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

✖ 1 problem (1 error, 0 warnings)
```

**Comment by jay-bulk** [comment]
@meyfa 
1. We've looked into this. We're not entirely sure that this is a breaking change, we are sorry if it is. At this point debating the reality of a breaking change is somewhat irrelevant because the release has been made.
2. This usage:

    ```yaml
    extends: standard
    overrides:
      - files: ['*.ts', '*.tsx']
        extends: 'standard-with-typescript'
    parserOptions:
      project: './tsconfig.lint.json'
      ```
   doesn't seem quite right because the `parserOptions.project` property applies only to the typescript-eslint parser, which the standard config doesn't use.

4. Consider finding a way to use your `tsconfig.json` for eslint. You may not be able to.
5. If you're using the same `tsconfig.lint.json` path in all downstream projects consider setting it in your shared eslint configuration.
6. Another breaking change is planned. That is the migration to the eslint flat configuration format. Consider deferring your upgrade until that is released to minimize workload.
